@_spi(ColonyInternal) import HiveCore

@_spi(ColonyInternal) public typealias AnyHiveChannelSpec<Schema: HiveSchema> = HiveCore.AnyHiveChannelSpec<Schema>
@_spi(ColonyInternal) public typealias AnyHiveCheckpointStore<Schema: HiveSchema> = HiveCore.AnyHiveCheckpointStore<Schema>
@_spi(ColonyInternal) public typealias AnyHiveModelClient = HiveCore.AnyHiveModelClient
@_spi(ColonyInternal) public typealias AnyHiveToolRegistry = HiveCore.AnyHiveToolRegistry
@_spi(ColonyInternal) public typealias AnyHiveWrite<Schema: HiveSchema> = HiveCore.AnyHiveWrite<Schema>
@_spi(ColonyInternal) public typealias CompiledHiveGraph<Schema: HiveSchema> = HiveCore.CompiledHiveGraph<Schema>
@_spi(ColonyInternal) public typealias HiveAnyCodec = HiveCore.HiveAnyCodec
@_spi(ColonyInternal) public typealias HiveChannelID = HiveCore.HiveChannelID
@_spi(ColonyInternal) public typealias HiveChannelKey<Schema: HiveSchema, Value: Sendable> = HiveCore.HiveChannelKey<Schema, Value>
@_spi(ColonyInternal) public typealias HiveChannelSpec<Schema: HiveSchema, Value: Sendable> = HiveCore.HiveChannelSpec<Schema, Value>
@_spi(ColonyInternal) public typealias HiveChatMessage = HiveCore.HiveChatMessage
@_spi(ColonyInternal) public typealias HiveChatMessageOp = HiveCore.HiveChatMessageOp
@_spi(ColonyInternal) public typealias HiveChatRequest = HiveCore.HiveChatRequest
@_spi(ColonyInternal) public typealias HiveChatResponse = HiveCore.HiveChatResponse
@_spi(ColonyInternal) public typealias HiveChatRole = HiveCore.HiveChatRole
@_spi(ColonyInternal) public typealias HiveChatStreamChunk = HiveCore.HiveChatStreamChunk
@_spi(ColonyInternal) public typealias HiveCheckpoint<Schema: HiveSchema> = HiveCore.HiveCheckpoint<Schema>
@_spi(ColonyInternal) public typealias HiveCheckpointID = HiveCore.HiveCheckpointID
@_spi(ColonyInternal) public typealias HiveCheckpointPolicy = HiveCore.HiveCheckpointPolicy
@_spi(ColonyInternal) public typealias HiveCheckpointQueryableStore = HiveCore.HiveCheckpointQueryableStore
@_spi(ColonyInternal) public typealias HiveCheckpointStore = HiveCore.HiveCheckpointStore
@_spi(ColonyInternal) public typealias HiveCheckpointSummary = HiveCore.HiveCheckpointSummary
@_spi(ColonyInternal) public typealias HiveClock = HiveCore.HiveClock
@_spi(ColonyInternal) public typealias HiveEnvironment<Schema: HiveSchema> = HiveCore.HiveEnvironment<Schema>
@_spi(ColonyInternal) public typealias HiveEvent = HiveCore.HiveEvent
@_spi(ColonyInternal) public typealias HiveEventID = HiveCore.HiveEventID
@_spi(ColonyInternal) public typealias HiveEventKind = HiveCore.HiveEventKind
@_spi(ColonyInternal) public typealias HiveGlobalStore<Schema: HiveSchema> = HiveCore.HiveGlobalStore<Schema>
@_spi(ColonyInternal) public typealias HiveGraphBuilder<Schema: HiveSchema> = HiveCore.HiveGraphBuilder<Schema>
@_spi(ColonyInternal) public typealias HiveInferenceHints = HiveCore.HiveInferenceHints
@_spi(ColonyInternal) public typealias HiveInputContext = HiveCore.HiveInputContext
@_spi(ColonyInternal) public typealias HiveInterruption<Schema: HiveSchema> = HiveCore.HiveInterruption<Schema>
@_spi(ColonyInternal) public typealias HiveInterruptID = HiveCore.HiveInterruptID
@_spi(ColonyInternal) public typealias HiveInterruptRequest<Schema: HiveSchema> = HiveCore.HiveInterruptRequest<Schema>
@_spi(ColonyInternal) public typealias HiveJSONCodec<Value: Codable & Sendable> = HiveCore.HiveJSONCodec<Value>
@_spi(ColonyInternal) public typealias HiveLogger = HiveCore.HiveLogger
@_spi(ColonyInternal) public typealias HiveModelClient = HiveCore.HiveModelClient
@_spi(ColonyInternal) public typealias HiveModelRouter = HiveCore.HiveModelRouter
@_spi(ColonyInternal) public typealias HiveNext = HiveCore.Route
@_spi(ColonyInternal) public typealias HiveNode<Schema: HiveSchema> = HiveCore.NodeAction<Schema>
@_spi(ColonyInternal) public typealias HiveNodeID = HiveCore.HiveNodeID
@_spi(ColonyInternal) public typealias HiveNodeInput<Schema: HiveSchema> = HiveCore.HiveNodeInput<Schema>
@_spi(ColonyInternal) public typealias HiveNodeOutput<Schema: HiveSchema> = HiveCore.HiveNodeOutput<Schema>
@_spi(ColonyInternal) public typealias HiveOutputProjection = HiveCore.HiveOutputProjection
@_spi(ColonyInternal) public typealias HiveProjectedChannelValue = HiveCore.HiveProjectedChannelValue
@_spi(ColonyInternal) public typealias HiveReducer<Value: Sendable> = HiveCore.HiveReducer<Value>
@_spi(ColonyInternal) public typealias HiveRouter<Schema: HiveSchema> = HiveCore.HiveRouter<Schema>
@_spi(ColonyInternal) public typealias HiveRunCancellationCause = HiveCore.HiveRunCancellationCause
@_spi(ColonyInternal) public typealias HiveRunHandle<Schema: HiveSchema> = HiveCore.HiveRunHandle<Schema>
@_spi(ColonyInternal) public typealias HiveRunID = HiveCore.HiveRunID
@_spi(ColonyInternal) public typealias HiveRunOptions = HiveCore.HiveRunOptions
@_spi(ColonyInternal) public typealias HiveRunOutcome<Schema: HiveSchema> = HiveCore.HiveRunOutcome<Schema>
@_spi(ColonyInternal) public typealias HiveRunOutput<Schema: HiveSchema> = HiveCore.HiveRunOutput<Schema>
@_spi(ColonyInternal) public typealias HiveRunAttemptID = HiveCore.HiveRunAttemptID
@_spi(ColonyInternal) public typealias HiveRuntime<Schema: HiveSchema> = HiveCore.HiveRuntime<Schema>
@_spi(ColonyInternal) public typealias HiveRuntimeError = HiveCore.HiveRuntimeError
@_spi(ColonyInternal) public typealias HiveSchema = HiveCore.HiveSchema
@_spi(ColonyInternal) public typealias HiveSnapshotValue = HiveCore.HiveSnapshotValue
@_spi(ColonyInternal) public typealias HiveStoreView<Schema: HiveSchema> = HiveCore.HiveStoreView<Schema>
@_spi(ColonyInternal) public typealias HiveStreamingMode = HiveCore.HiveStreamingMode
@_spi(ColonyInternal) public typealias HiveTaskID = HiveCore.HiveTaskID
@_spi(ColonyInternal) public typealias HiveTaskLocalStore<Schema: HiveSchema> = HiveCore.HiveTaskLocalStore<Schema>
@_spi(ColonyInternal) public typealias HiveTaskSeed = HiveCore.HiveTaskSeed
@_spi(ColonyInternal) public typealias HiveThreadID = HiveCore.HiveThreadID
@_spi(ColonyInternal) public typealias HiveToolCall = HiveCore.HiveToolCall
@_spi(ColonyInternal) public typealias HiveToolDefinition = HiveCore.HiveToolDefinition
@_spi(ColonyInternal) public typealias HiveToolRegistry = HiveCore.HiveToolRegistry
@_spi(ColonyInternal) public typealias HiveToolResult = HiveCore.HiveToolResult
